sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
dist: trusty
language: node_js
node_js:
  - "10"
install:
  - yarn
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
script:
  # - cd native; yarn test; cd --
  - cd web >/dev/null 2>&1; yarn test:ci; cd -- >/dev/null 2>&1;
